### ISSUE TITLE
64 bit version?

### ISSUE THREAD

**Issue by funky-monkey** [katopz/ane-photosalbum#4]
Hello, 
Since Apple onl accepts 64bit apps, i have to rebuild my app. 
I have tried creating a 64 bit version from your source, but i have failed. I have tried to create a aggregate target, updated the extension.xml to have iPhone-ARM and iPhone-x86, but when i run your build script, it keeps saying 'Missing native library implementation 'libPhotosAlbum.a' for platform: iPhone-ARM'

Could you help me and create a universal 64 bit version of your ANE extension?

your help is much appreciated, 

Best, 
Sidney

**Comment by katopz** [comment]
@funky-monkey Consider it done! and don't for get to [feed](https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=katopz%40gmail%2ecom&lc=TH&item_name=tuna&item_number=tuna&button_subtype=services&no_note=0&currency_code=USD&bn=PP%2dBuyNowBF%3abtn_buynowCC_LG%2egif%3aNonHostedGuest) my cats ;)

here's what to be done : https://github.com/katopz/ane-photosalbum/commit/473f0cd8fb52ed19879c2c2355a05ad7985b286c

FYI : here's fun part in case you feeling brave http://sleepydesign.blogspot.com/2015/01/air-how-to-build-ane-64-bit.html

**Comment by funky-monkey** [comment]
Your cats are fed ;-)

Thanks for the article as well, very nice!

**Comment by katopz** [comment]
@funky-monkey Many thanks! You just made my day! :smile_cat:
